import supertest from 'supertest'
import bcrypt from 'bcrypt'
import app from '../app.js'

const api = supertest(app.attach)
const autorization = 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NTdmODU2NWFiMTI1NzQwZmM4ZDk0OSIsImRuaSI6IjI5OTc5MjQzIiwiaWF0IjoxNjgzNDk0NzI5fQ.J5K_4wOJzaw3bDryLRg2lQ71oSb0lf2-57V1Cooqssc'
const users = [
  {
    dni: '13488315',
    code: '93156404',
    email: 'user@email.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'José Luis',
    lastnames: 'Morales Vasquez',
    phone: '+58 426-905-9863',
    profilePictureURL: '/images/users/4.jpg',
    department: 'Unidad de Neurología y Neurocirugía',
    specialty: 'Neurólogo',
    isAdmin: true,
    isActive: true
  },
  {
    dni: '15104832',
    code: '40317251',
    email: 'julio.g.morales@gmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Julio Armando',
    lastnames: 'Gómez Martínez',
    phone: '+58 424-881-6094',
    profilePictureURL: '/images/users/17.jpg',
    specialty: 'Neurólogo',
    isAdmin: false,
    isActive: true,
    department: 'Unidad de Neurología y Neurocirugía'
  },
  {
    dni: '17343109',
    code: '94700573',
    email: 'leyda.m.velazco@yahoo.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Leyda Margarita',
    lastnames: 'Velazco',
    phone: '+58 426-940-4305',
    profilePictureURL: '/images/users/1.jpg',
    department: 'Unidad de Psiquiatría',
    specialty: 'Psiquiatra',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '21751500',
    code: '26528479',
    email: 'misaelDavid.s.madriz@hotmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Misael David',
    lastnames: 'Salazar Madríz',
    phone: '+58 416-091-3704',
    profilePictureURL: '/images/users/2.jpg',
    department: 'Unidad de Hematología e Inmunología',
    specialty: 'Inmunólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '12099858',
    code: '84901124',
    email: 'yajaira.j.zarraga@gmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Yajaira Josefina',
    lastnames: 'Zarraga',
    phone: '+58 412-256-7581',
    profilePictureURL: '/images/users/3.jpg',
    department: 'Unidad de Psiquiatría',
    specialty: 'Psiquiatra',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '13425862',
    code: '59123025',
    email: 'tulio.r.lugo@hotmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Tulio Rafael',
    lastnames: 'Lugo',
    phone: '+58 424-876-5419',
    profilePictureURL: '/images/users/5.jpg',
    department: 'Unidad Respiratoria',
    specialty: 'Neumonólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '17834901',
    code: '12523148',
    email: 'roberto.a.gonzalez@hotmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Roberto Antonio',
    lastnames: 'González',
    phone: '+58 424-696-3471',
    profilePictureURL: '/images/users/6.jpg',
    department: 'Unidad Respiratoria',
    specialty: 'Neumonólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '19154542',
    code: '29715094',
    email: 'richard.a.seferen@yahoo.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Richard Alexander',
    lastnames: 'Seferen',
    phone: '+58 412-467-5207',
    profilePictureURL: '/images/users/7.jpg',
    department: 'Unidad de Neurología y Neurocirugía',
    specialty: 'Neurólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '18425641',
    code: '01168979',
    email: 'rosmary.c.p.arteaga@gmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Rosmary Coromoto',
    lastnames: 'Palencia Arteaga',
    phone: '+58 412-606-6034',
    profilePictureURL: '/images/users/8.jpg',
    department: 'Unidad de Hematología e Inmunología',
    specialty: 'Inmunólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '9156017',
    code: '99482491',
    email: 'miguel.a.sangronis@gmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Miguel Angel',
    lastnames: 'Sangronis',
    phone: '+58 426-815-3025',
    profilePictureURL: '/images/users/9.jpg',
    department: 'Unidad Respiratoria',
    specialty: 'Neumonólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '13599444',
    code: '23263824',
    email: 'gladys.v.ventura@gmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Gladys',
    lastnames: 'Vargas Ventura',
    phone: '+58 412-137-0598',
    profilePictureURL: '/images/users/10.jpg',
    department: 'Unidad Respiratoria',
    specialty: 'Neumonólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '9511607',
    code: '23481248',
    email: 'henry.j.c.sanchez@gmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Henry José',
    lastnames: 'Chirinos Sánchez',
    phone: '+58 426-522-4680',
    profilePictureURL: '/images/users/11.jpg',
    department: 'Unidad de Neurología y Neurocirugía',
    specialty: 'Neurólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '24408937',
    code: '82897777',
    email: 'morelba.gomez@gmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Morelba',
    lastnames: 'Gómez',
    phone: '+58 426-511-3183',
    profilePictureURL: '/images/users/12.jpg',
    department: 'Unidad de Hematología e Inmunología',
    specialty: 'Inmunólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '11151424',
    code: '09252957',
    email: 'beatriz.g.herrera@hotmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Beatriz',
    lastnames: 'García Herrera',
    phone: '+58 414-125-3022',
    profilePictureURL: '/images/users/13.jpg',
    department: 'Unidad de Neurología y Neurocirugía',
    specialty: 'Neurólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '19724055',
    code: '37862308',
    email: 'eira.l.v.curiel@yahoo.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Eira Lisbeth',
    lastnames: 'Ventura Curiel',
    phone: '+58 424-735-2342',
    profilePictureURL: '/images/users/14.jpg',
    department: 'Unidad de Psiquiatría',
    specialty: 'Psiquiatra',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '19381990',
    code: '72780116',
    email: 'pedro.p.polanco@gmail.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Pedro Pablo',
    lastnames: 'Polanco',
    phone: '+58 412-252-1384',
    profilePictureURL: '/images/users/15.jpg',
    department: 'Unidad Respiratoria',
    specialty: 'Neumonólogo',
    isAdmin: false,
    isActive: true
  },
  {
    dni: '9293796',
    code: '93038331',
    email: 'luis.a.d.garcia@yahoo.com',
    password: bcrypt.hashSync('12345678', 10),
    firstnames: 'Luis Alberto',
    lastnames: 'Durante García',
    phone: '+58 416-421-2662',
    profilePictureURL: '/images/users/16.jpg',
    department: 'Unidad de Hematología e Inmunología',
    specialty: 'Inmunólogo',
    isAdmin: false,
    isActive: true
  }
]

export { api, users, autorization }
